[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/bin/console messenger:consume async -vv --time-limit=3600
directory=/var/www/html
autostart=false
autorestart=true
startretries=3
numprocs=8
user=appuser
stdout_logfile=/var/log/supervisor/worker_%(process_num)02d.log
stderr_logfile=/var/log/supervisor/worker_%(process_num)02d_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5
environment=ASYNC_MODE="true",MESSENGER_TRANSPORT_DSN="redis://redis:6379/messages"

